version: "3.7"

services:
  server:
    build: app
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    networks:
      AIservice:
        aliases:
          - server.docker

  frontend:
    build: frontend
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 3000
    ports:
      - 3000:3000
    networks:
      AIservice:
        aliases:
          - frontend.docker
    depends_on:
      - server

networks:
  AIservice:
    external: true
